### PR TITLE
Sync puppet_agent install script, add debian 12 to litmus tests

### PR DESCRIPTION
**Pull request by linuxdaemon**
This PR bumps the puppet_agent module version to include support for Debian Bookworm.

This fixes #7

This was generated by updating the puppet_agent submodule and running `ruby install.rb`.

### CODE REVIEW

**Comment by joshcooper** [comment]
@span786 Were you about to look into this?

**Comment by span786** [comment]
Changes for debian-12-x86-64 were taken care in https://github.com/puppetlabs/install-puppet/pull/20

**Comment by joshcooper** [comment]
@linuxdaemon could you update your PR to include the litmus and Perl changes?

**Comment by kenyon** [comment]
I think this is blocking support for Debian 12 in puppetlabs modules, like https://github.com/puppetlabs/puppetlabs-apt/pull/1178 for example.

**Comment by joshcooper** [comment]
Hi @linuxdaemon Thanks for updating the `install-puppet.sh` script to match what's in the `puppet_agent` module, but I'm not following the part about "adds bookworm support". Wasn't that handled https://github.com/puppetlabs/install-puppet/pull/20/files#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44fR871?

Separately, I think there is a issue with https://apt.puppet.com/puppet-release-bookworm.deb that `install-puppet.sh` downloads by default. It seems to install an old version of puppet-agent from debian's repos(!)

```
$ docker run -it debian:bookworm /bin/bash
root@e3f41b5a291d:/# apt-get update
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8786 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [13.8 kB]
Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [156 kB]
Fetched 9210 kB in 1s (11.2 MB/s)                       
Reading package lists... Done
root@e3f41b5a291d:/# apt install curl
...
root@e3f41b5a291d:/# curl -LO https://raw.githubusercontent.com/puppetlabs/install-puppet/619cedb37831114f6499a429e473296925c8b40c/install.sh
...
root@e3f41b5a291d:/# bash install.sh 
05:21:40 +0000 INFO: Version parameter not defined and no agent detected. Assuming latest.
05:21:40 +0000 INFO: Downloading Puppet latest for Debian...
05:21:40 +0000 INFO: Debian platform! Lets get you a DEB...
05:21:40 +0000 INFO: Downloading http://apt.puppet.com/puppet-release-bookworm.deb
05:21:40 +0000 INFO:   to file /tmp/install.sh.2841.924572179/puppet-release-bookworm.deb
05:21:40 +0000 INFO: Trying curl...
05:21:41 +0000 INFO: Installing puppetlabs apt repo with dpkg...
Selecting previously unselected package puppet-release.
(Reading database ... 6745 files and directories currently installed.)
Preparing to unpack .../puppet-release-bookworm.deb ...
Unpacking puppet-release (1.0.0-31bookworm) ...
Setting up puppet-release (1.0.0-31bookworm) ...
Get:1 http://apt.puppet.com bookworm InRelease [56.2 kB]
Get:2 http://apt.puppet.com bookworm/puppet all Packages [517 B]
Get:3 http://apt.puppet.com bookworm/puppet amd64 Packages [517 B]            
Hit:4 http://deb.debian.org/debian bookworm InRelease  
Hit:5 http://deb.debian.org/debian bookworm-updates InRelease
Hit:6 http://deb.debian.org/debian-security bookworm-security InRelease
...
Get:32 http://deb.debian.org/debian bookworm/main amd64 puppet-agent all 7.23.0-1 [1147 kB]
root@e3f41b5a291d:/# which puppet
/usr/bin/puppet
root@e3f41b5a291d:/# puppet --version
7.23.0
```

If I manually install the `puppet7-release-bookworm.deb` package then it works:

```
$ docker run -it -v `pwd`:/root debian:bookworm /bin/bash
root@a9f00190986d:/# dpkg -i /root/puppet7-release-bookworm.deb 
Selecting previously unselected package puppet7-release.
(Reading database ... 6090 files and directories currently installed.)
Preparing to unpack .../puppet7-release-bookworm.deb ...
Unpacking puppet7-release (7.0.0-17bookworm) ...
Setting up puppet7-release (7.0.0-17bookworm) ...
root@a9f00190986d:/# apt-get update
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8786 kB]
Get:5 http://apt.puppet.com bookworm InRelease [56.2 kB]
Get:6 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [13.8 kB]
Get:7 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [156 kB]
Get:8 http://apt.puppet.com bookworm/puppet7 all Packages [715 B]
Get:9 http://apt.puppet.com bookworm/puppet7 amd64 Packages [21.5 kB]
Fetched 9289 kB in 1s (11.1 MB/s)                         
Reading package lists... Done
root@a9f00190986d:/# apt install puppet-agent 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  puppet-agent
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 30.8 MB of archives.
After this operation, 109 MB of additional disk space will be used.
Get:1 http://apt.puppet.com bookworm/puppet7 amd64 puppet-agent amd64 7.30.0-1bookworm [30.8 MB]
```

I will check with release engineering about `puppet-release-bookworm.deb`

**Comment by linuxdaemon** [comment]
Hey @joshcooper, not sure re: old version of puppet installed, that is odd. but re: "adds bookworm support", yes that was added in #20, this PR was originally set up to implement those changes, but I have updated the title to reflect the new limited set of changes

**Pull request merged**
